## 1: You are given two sentences as strings.
Create a function that returns a list of all words that are not in both sentences.
You can assume that the sentences have no punctuation marks, extra tabs, or spaces.

Note: The strings "Game" and "game" should be considered the same word. Because of this, make sure all the strings in the list you output are in lowercase.

Example:
Input:

string1 = "I want to eat fish today with my friends"
string2 = "All I want is to eat fish today with my friends"
Output:
def mismatched_words(string1,string2) -> ["all","is"].

In [15]:
string1 = "I want to eat fish today with my friends" 
string2 = "All I want is to eat fish today with my friends" 

print(string1.lower().split())

print(string2.lower().split())

print(set(string1.lower().split()))
print(set(string2.lower().split()))

['i', 'want', 'to', 'eat', 'fish', 'today', 'with', 'my', 'friends']
['all', 'i', 'want', 'is', 'to', 'eat', 'fish', 'today', 'with', 'my', 'friends']
{'my', 'want', 'to', 'today', 'friends', 'fish', 'with', 'eat', 'i'}
{'all', 'is', 'my', 'want', 'to', 'today', 'friends', 'fish', 'with', 'eat', 'i'}

In [19]:
def mismatched_words(string1,string2):
    words1=set(string1.lower().split())
    words2=set(string2.lower().split())
    mismatched=words1.symmetric_difference(words2)
    return list(mismatched)

In [20]:
mismatched_words(string1,string2)

['all', 'is']

## 2: You are given a string that resembles the declaration of a list of dictionaries.

Without using the pandas package, write a function read_split_from_str to split the data into two lists, one for training and one for testing,
with a 70:30 split between the training set and the testing set.

Note: Use numpy for random number generation if you need to.
Example
Input:
list_of_dict_str = "[{'x': 0.0, 'y': 5.43}, {'x': 50.0, 'y': 102.78}, {'x': 100.0, 'y': 204.24}]"

In [34]:
def read_split_from_str(list_of_dict_str):
    list_of_dict = eval(list_of_dict_str)
    split_point = len(list_of_dict) * 7 // 10
    return [list_of_dict[split_point:], list_of_dict[:split_point]]

In [35]:
read_split_from_str(list_of_dict_str)

[[{'x': 100.0, 'y': 204.24}],
 [{'x': 0.0, 'y': 5.43}, {'x': 50.0, 'y': 102.78}]]

## 3: Write a function to impute the mode Name of the selected Name in place of the missing values.

In [88]:
import pandas as pd
data=[
    {'Name':'Mike','Age':48,'Salary':None},
    {'Name':'John','Age':38,'Salary':6800},
    {'Name':'fidel','Age':25,'Salary':7000},
    {'Name':'tom','Age':35,'Salary':7000},
    {'Name':None,'Age':25,'Salary':7000},
    {'Name':'Freeman','Age':76,'Salary':4500}]

dftest=pd.DataFrame(data)

In [89]:
dftest

      Name  Age  Salary
0     Mike   48     NaN
1     John   38  6800.0
2    fidel   25  7000.0
3      tom   35  7000.0
4     None   25  7000.0
5  Freeman   76  4500.0

In [90]:
dftest.isnull().sum()

Name      1
Age       0
Salary    1
dtype: int64

In [91]:
dftest['Name'].mode()

0    Freeman
1       John
2       Mike
3      fidel
4        tom
Name: Name, dtype: object

In [92]:
dftest['Name'].mode()[0]

'Freeman'

In [93]:
def name_mode(df):
    name_mode=df['Name'].mode()[0]
    df['Name']=df['Name'].fillna(name_mode)
    return df

In [94]:
name_mode(dftest)

      Name  Age  Salary
0     Mike   48     NaN
1     John   38  6800.0
2    fidel   25  7000.0
3      tom   35  7000.0
4  Freeman   25  7000.0
5  Freeman   76  4500.0

## 4: Write a function to select only the rows where the student’s favorite color is green or red and their grade is above 90.

In [114]:
data = {
    'Name': ['Nitish', 'Mike', 'John', 'Peter', 'Mathews'],
    'FavoriteColor': ['red', 'blue', 'green', 'green', 'yellow'],
    'Grade': [95, 88, 92, 85, 91]
}

student_df = pd.DataFrame(data)

def grade_color(df):
    filtered_df=df[df['FavoriteColor'].isin(['red','green']) & (df['Grade']> 90)]
    return filtered_df

In [115]:
grade_color(student_df)

     Name FavoriteColor  Grade
0  Nitish           red     95
2    John         green     92

## 5: You are given a dataset of students and their scores in a subject. Write a function that
<br>Adds two new columns to the DataFrame:
<br>One showing the rank of each student based on their score (highest score = rank 1), allowing gaps in rank.
    <br>Another showing the dense rank, where there are no gaps in ranking.
    <br>Returns the DataFrame sorted by Score in descending order.

In [118]:
data={
    'Student':['Nitish', 'Mike', 'John', 'Peter', 'Mathews','Pinto'],
    'Score':[95,80,95,70,60,80]
}

student_df=pd.DataFrame(data)
student_df

   Student  Score
0   Nitish     95
1     Mike     80
2     John     95
3    Peter     70
4  Mathews     60
5    Pinto     80

In [121]:
student_df['Rank']=student_df['Score'].rank(ascending=False,method='min')

In [122]:
student_df

   Student  Score  Rank
0   Nitish     95   1.0
1     Mike     80   3.0
2     John     95   1.0
3    Peter     70   5.0
4  Mathews     60   6.0
5    Pinto     80   3.0

In [124]:
student_df['Dense_Rank']=student_df['Score'].rank(ascending=False,method='dense')

In [125]:
student_df

   Student  Score  Rank  Dense_Rank
0   Nitish     95   1.0         1.0
1     Mike     80   3.0         2.0
2     John     95   1.0         1.0
3    Peter     70   5.0         3.0
4  Mathews     60   6.0         4.0
5    Pinto     80   3.0         2.0

In [130]:
def ranking(df):
    student_df.sort_values(by='Score',ascending=False).reset_index(drop=True)
    student_df['Rank']=student_df['Score'].rank(ascending=False,method='min')
    student_df['Dense_rank']=student_df['Score'].rank(ascending=False,method='dense')
    student_df['lag']=student_df['Score'].shift(1)
    student_df['lead']=student_df['Score'].shift(-1)
    return student_df

In [131]:
ranking(student_df)

   Student  Score  Rank  Dense_Rank  Dense_rank   lag  lead
0   Nitish     95   1.0         1.0         1.0   NaN  80.0
1     Mike     80   3.0         2.0         2.0  95.0  95.0
2     John     95   1.0         1.0         1.0  80.0  70.0
3    Peter     70   5.0         3.0         3.0  95.0  60.0
4  Mathews     60   6.0         4.0         4.0  70.0  80.0
5    Pinto     80   3.0         2.0         2.0  60.0   NaN

## 6:  You are given an employee dataset with a column named Salary. Your task is to:
<br>Write a function salary_category(salary) that classifies salaries into:
<br>'Low' if salary is less than 70,000
<br>'Medium' if salary is between 70,000 and 79,999
<br>'High' if salary is 80,000 or more
<br>Apply this function to create a new column called "Salary Category" in the DataFrame df_employees.
<br>Display the updated DataFrame.

In [140]:
data={
    'Name':['Nitish','John','Mike','Mathew','Johny','Tom'],
    'salary':[100000,75000,65000,90000,77000,45000]
}

In [141]:
salary_df=pd.DataFrame(data)

In [142]:
salary_df

     Name  salary
0  Nitish  100000
1    John   75000
2    Mike   65000
3  Mathew   90000
4   Johny   77000
5     Tom   45000

In [145]:
def salary_category(salary):
    if salary < 70000:
        return 'low'
    elif 70000 <= salary < 80000:
        return 'medium'
    else : 
        return 'High'

# Apply the function to create a new column*

salary_df['Salary_grades']=salary_df['salary'].apply(salary_category)

In [146]:
salary_df

     Name  salary Salary_grades
0  Nitish  100000          High
1    John   75000        medium
2    Mike   65000           low
3  Mathew   90000          High
4   Johny   77000        medium
5     Tom   45000           low

## 7:Count Elements in List with Dictionary Output

You are given a list of departments. Write a function that returns a dictionary with department names as keys and their count as values.

departments = ['Data', 'HR', 'Data', 'Finance', 'HR', 'HR']

In [147]:
departments = ['Data', 'HR', 'Data', 'Finance', 'HR', 'HR']

In [151]:
from collections import Counter

department_counter=Counter(departments)
department_counter

Counter({'HR': 3, 'Data': 2, 'Finance': 1})

## 8: Top-N Dictionary Values

Write a function to return the top 2 highest-paid employees from the dictionary of names and salaries.

salaries = {
    'Alice': 85000,
    'Tyson': 75000,
    'Morgan': 92000,
    'Megan': 88000
}

In [152]:
salaries = {
    'Alice': 85000,
    'Tyson': 75000,
    'Morgan': 92000,
    'Megan': 88000
}

In [159]:
print(salaries.keys())
print(salaries.values())

dict_keys(['Alice', 'Tyson', 'Morgan', 'Megan'])
dict_values([85000, 75000, 92000, 88000])

In [164]:
salaries.items()

dict_items([('Alice', 85000), ('Tyson', 75000), ('Morgan', 92000), ('Megan', 88000)])

In [167]:
sorted_by_keys=dict(sorted(salaries.items()))

In [168]:
sorted_by_keys

{'Alice': 85000, 'Megan': 88000, 'Morgan': 92000, 'Tyson': 75000}

In [170]:
sorted_by_values=dict(sorted(salaries.items(),key=lambda item:item[1]))

In [171]:
sorted_by_values

{'Tyson': 75000, 'Alice': 85000, 'Megan': 88000, 'Morgan': 92000}

In [173]:
sorted_by_values_reverse=dict(sorted(salaries.items(),key=lambda item:item[1],reverse=True))

In [174]:
sorted_by_values_reverse

{'Morgan': 92000, 'Megan': 88000, 'Alice': 85000, 'Tyson': 75000}

## 9: Write a function f() that takes a number and returns that number increased by 2. Then, apply this function to the "col1" column and store the result in a new column named "col3".

In [176]:
data= {
    'col1':[2,3,4,5],
    'col2':['A','B','C','D']
}

In [177]:
df=pd.DataFrame(data)

In [178]:
df

   col1 col2
0     2    A
1     3    B
2     4    C
3     5    D

In [183]:
def f(num):
    return num + 2
df['col3']=df['col1'].apply(f)

In [184]:
df

   col1 col2  col3
0     2    A     4
1     3    B     5
2     4    C     6
3     5    D     7

## 10: Given a DataFrame with a Salary column, identify outliers using the IQR (Interquartile Range) method.

In [185]:
data={
    'salary':[45000, 47000, 48000, 50000, 52000, 150000, 55000, 60000, 62000]
}

In [189]:
df=pd.DataFrame(data)

In [190]:
df

   salary
0   45000
1   47000
2   48000
3   50000
4   52000
5  150000
6   55000
7   60000
8   62000

In [194]:
#IQR Method
Q1=df['salary'].quantile(0.25)
Q3=df['salary'].quantile(0.75)

IQR=Q3 - Q1

In [195]:
Q1

np.float64(48000.0)

In [196]:
Q3

np.float64(60000.0)

In [197]:
IQR

np.float64(12000.0)

In [199]:
lower_bound=Q1-1.5*IQR
Upper_bound=Q3+1.5*IQR

In [202]:
Outliers=df[(df['salary'] < lower_bound) | (df['salary'] > Upper_bound)]

In [203]:
Outliers

   salary
5  150000

## 11: find Columns with >30% Missing Values

In [206]:
import numpy as np
data = {
    'Name': ['Alice', 'Bob', 'Prince', 'David', 'Balu', 'Jackson', 'Grace'],
    'Age': [25, 30, np.nan, 40, 29, np.nan, np.nan],
    'Salary': [50000, 54000, 60000, np.nan, np.nan, np.nan, np.nan],
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance', 'HR']
}

In [208]:
df=pd.DataFrame(data)

In [209]:
df

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob  30.0  54000.0         IT
2   Prince   NaN  60000.0         HR
3    David  40.0      NaN         IT
4     Balu  29.0      NaN    Finance
5  Jackson   NaN      NaN    Finance
6    Grace   NaN      NaN         HR

In [214]:
missing_ratio=df.isnull().mean()

In [221]:
high_missing_cols=missing_ratio[missing_ratio > 0.3].index.to_list()

In [223]:
print("columns with more that 30% Missing Values:", high_missing_cols)

columns with more that 30% Missing Values: ['Age', 'Salary']

## 12: Fill missing Salary values using the average salary of the same Department.

In [224]:
#Impute missing Salary with department-wise mean

import numpy as np
data = {
    'Name': ['Alice', 'Bob', 'Prince', 'David', 'Balu', 'Jackson', 'Grace'],
    'Age': [25, 30, np.nan, 40, 29, np.nan, np.nan],
    'Salary': [50000, 54000, 60000, np.nan, np.nan, np.nan, np.nan],
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance', 'HR']
}

df=pd.DataFrame(data)

In [225]:
df

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob  30.0  54000.0         IT
2   Prince   NaN  60000.0         HR
3    David  40.0      NaN         IT
4     Balu  29.0      NaN    Finance
5  Jackson   NaN      NaN    Finance
6    Grace   NaN      NaN         HR

In [227]:
df['Salary'] = df.groupby('Department')['Salary'].transform(lambda x: x.fillna(x.mean()))

In [228]:
df

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob  30.0  54000.0         IT
2   Prince   NaN  60000.0         HR
3    David  40.0  54000.0         IT
4     Balu  29.0      NaN    Finance
5  Jackson   NaN      NaN    Finance
6    Grace   NaN  55000.0         HR